#!/bin/bash
sudo adduser jenkins &>/dev/null
sudo runuser -l jenkins -c 'mkdir -p ~/.ssh'
sudo runuser -l jenkins -c 'chmod -R 700 ~/.ssh'
sudo runuser -l jenkins -c 'cd ~/.ssh'
sudo runuser -l jenkins -c 'cp /vagrant/id_rsa ~/.ssh/'
sudo runuser -l jenkins -c 'chmod 600 ~/.ssh/id_rsa'